name: Build and push to Docker Hub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Read project name
        id: project_name
        run: |
          PROJECT_NAME=$(grep -o 'PROJECT_NAME="[^"]*"' .env.production | cut -d'"' -f2)
          echo "project_name=${PROJECT_NAME// /-}" >> $GITHUB_OUTPUT

      - name: Build Image
        run: |
          make docker-build-env ENV=production
          docker tag fastapi-langgraph-template:production ${{ secrets.DOCKER_USERNAME }}/${{ steps.project_name.outputs.project_name }}:production

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ steps.project_name.outputs.project_name }}:production
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
